name: Retrigger

on:
  issue_comment:
    types:
      - created

jobs:
  retrigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/trigger-action-by-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: ${{ github.event.issue.number }}
          comment: ${{ github.event.comment.body }}
