name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "test"
      - uses: ./.github/actions/trigger-action-by-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: 100
          comment: "trigger lint"
