name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/rerun-workflow-by-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: ${{ github.event.issue.number }}
          comment: ${{ github.event.comment.body }}
